/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SantosRouteImport } from './routes/santos'
import { Route as OracoesRouteImport } from './routes/oracoes'
import { Route as NovenasRouteImport } from './routes/novenas'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as LiturgiaRouteImport } from './routes/liturgia'
import { Route as CatequeseRouteImport } from './routes/catequese'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SantosSlugRouteImport } from './routes/santos.$slug'
import { Route as NovenasSlugRouteImport } from './routes/novenas.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SantosRoute = SantosRouteImport.update({
  id: '/santos',
  path: '/santos',
  getParentRoute: () => rootRouteImport,
} as any)
const OracoesRoute = OracoesRouteImport.update({
  id: '/oracoes',
  path: '/oracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const NovenasRoute = NovenasRouteImport.update({
  id: '/novenas',
  path: '/novenas',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const LiturgiaRoute = LiturgiaRouteImport.update({
  id: '/liturgia',
  path: '/liturgia',
  getParentRoute: () => rootRouteImport,
} as any)
const CatequeseRoute = CatequeseRouteImport.update({
  id: '/catequese',
  path: '/catequese',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SantosSlugRoute = SantosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SantosRoute,
} as any)
const NovenasSlugRoute = NovenasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NovenasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/catequese': typeof CatequeseRoute
  '/liturgia': typeof LiturgiaRoute
  '/noticias': typeof NoticiasRoute
  '/novenas': typeof NovenasRouteWithChildren
  '/oracoes': typeof OracoesRoute
  '/santos': typeof SantosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/novenas/$slug': typeof NovenasSlugRoute
  '/santos/$slug': typeof SantosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/catequese': typeof CatequeseRoute
  '/liturgia': typeof LiturgiaRoute
  '/noticias': typeof NoticiasRoute
  '/novenas': typeof NovenasRouteWithChildren
  '/oracoes': typeof OracoesRoute
  '/santos': typeof SantosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/novenas/$slug': typeof NovenasSlugRoute
  '/santos/$slug': typeof SantosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/catequese': typeof CatequeseRoute
  '/liturgia': typeof LiturgiaRoute
  '/noticias': typeof NoticiasRoute
  '/novenas': typeof NovenasRouteWithChildren
  '/oracoes': typeof OracoesRoute
  '/santos': typeof SantosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/novenas/$slug': typeof NovenasSlugRoute
  '/santos/$slug': typeof SantosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/catequese'
    | '/liturgia'
    | '/noticias'
    | '/novenas'
    | '/oracoes'
    | '/santos'
    | '/sitemap.xml'
    | '/novenas/$slug'
    | '/santos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/catequese'
    | '/liturgia'
    | '/noticias'
    | '/novenas'
    | '/oracoes'
    | '/santos'
    | '/sitemap.xml'
    | '/novenas/$slug'
    | '/santos/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/catequese'
    | '/liturgia'
    | '/noticias'
    | '/novenas'
    | '/oracoes'
    | '/santos'
    | '/sitemap.xml'
    | '/novenas/$slug'
    | '/santos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  CatequeseRoute: typeof CatequeseRoute
  LiturgiaRoute: typeof LiturgiaRoute
  NoticiasRoute: typeof NoticiasRoute
  NovenasRoute: typeof NovenasRouteWithChildren
  OracoesRoute: typeof OracoesRoute
  SantosRoute: typeof SantosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santos': {
      id: '/santos'
      path: '/santos'
      fullPath: '/santos'
      preLoaderRoute: typeof SantosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracoes': {
      id: '/oracoes'
      path: '/oracoes'
      fullPath: '/oracoes'
      preLoaderRoute: typeof OracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novenas': {
      id: '/novenas'
      path: '/novenas'
      fullPath: '/novenas'
      preLoaderRoute: typeof NovenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liturgia': {
      id: '/liturgia'
      path: '/liturgia'
      fullPath: '/liturgia'
      preLoaderRoute: typeof LiturgiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catequese': {
      id: '/catequese'
      path: '/catequese'
      fullPath: '/catequese'
      preLoaderRoute: typeof CatequeseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santos/$slug': {
      id: '/santos/$slug'
      path: '/$slug'
      fullPath: '/santos/$slug'
      preLoaderRoute: typeof SantosSlugRouteImport
      parentRoute: typeof SantosRoute
    }
    '/novenas/$slug': {
      id: '/novenas/$slug'
      path: '/$slug'
      fullPath: '/novenas/$slug'
      preLoaderRoute: typeof NovenasSlugRouteImport
      parentRoute: typeof NovenasRoute
    }
  }
}

interface NovenasRouteChildren {
  NovenasSlugRoute: typeof NovenasSlugRoute
}

const NovenasRouteChildren: NovenasRouteChildren = {
  NovenasSlugRoute: NovenasSlugRoute,
}

const NovenasRouteWithChildren =
  NovenasRoute._addFileChildren(NovenasRouteChildren)

interface SantosRouteChildren {
  SantosSlugRoute: typeof SantosSlugRoute
}

const SantosRouteChildren: SantosRouteChildren = {
  SantosSlugRoute: SantosSlugRoute,
}

const SantosRouteWithChildren =
  SantosRoute._addFileChildren(SantosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  CatequeseRoute: CatequeseRoute,
  LiturgiaRoute: LiturgiaRoute,
  NoticiasRoute: NoticiasRoute,
  NovenasRoute: NovenasRouteWithChildren,
  OracoesRoute: OracoesRoute,
  SantosRoute: SantosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
